### ISSUE TITLE
[BUG] Highways and expressways (in Poland) have wrong `ref`

### ISSUE THREAD

**Issue by caspg** [onthegomap/planetiler#145]
**Describe the bug**
I noticed that highways and expressways in Poland have the wrong `ref`. Right now, they are using the ref value of the International road network ([network = "e-road"](https://en.wikipedia.org/wiki/International_E-road_network)). This is an example relation https://www.openstreetmap.org/relation/33702 from e-road network. And this is a relation that should be actually used for ref https://www.openstreetmap.org/relation/112778

It looks that the problem only happens for polish roads. For example, highways in Germany have correct local refs. 

**To Reproduce**

1. Download data from https://download.geofabrik.de/europe/poland/pomorskie.html
2. Run command `java -jar planetiler-dist/target/*with-deps.jar --force=true --osm-path=data/sources/pomorskie-latest.osm.pbf`
3. See error

**Expected behavior**

Relations that are part of `network="e-road` shouldn't be used for getting `ref` for transportation_name layer. Maybe 

**Screenshots**

Planetiler:
<img width="1121" alt="Screenshot 2022-03-23 at 10 31 08" src="https://user-images.githubusercontent.com/10419439/159667796-80bcf690-ad61-4840-83ef-c20333016854.png">

OMT:
<img width="859" alt="Screenshot 2022-03-23 at 10 31 28" src="https://user-images.githubusercontent.com/10419439/159667806-7401bee6-225e-45b0-b90d-009bf6792a33.png">

**Comment by msbarry** [comment]
Thanks @caspg, it looks like this is one of the ways you are talking about that exists in both relations: https://www.openstreetmap.org/way/536642248#map=14/54.2791/18.8608

I'm a little confused how openmaptiles is choosing S7 for the transportation name `ref` value since this logic appears to just take the ref value from route_1 if it's a valid route network?

https://github.com/openmaptiles/openmaptiles/blob/8693822d506076d1cbf0d777d40d3a0a12986ce6/layers/transportation_name/update_transportation_name.sql#L299-L303

**Comment by ZeLonewolf** [comment]
Huh, I'm surprised it works that way and I wrote the `route_N` functionality in OpenMapTiles.  If anything, I would say the planetiler output is the intended implementation and openmaptiles has a bug 🤔

**Comment by msbarry** [comment]
I think route_n is right but omt has logic to use refs preferring:

1. Major networks the way is a part of 
2. Ref tag on the way

Planetiler was using the ref from any network the way was a part of instead of the ref on the way. I changed it yo match omt's behavior, and added an optional flag to fall back to the ref from any relation if 1 and 2 are missing. 

Sounds like there may need to be some more complex handling in openmaptiles for this network type?
