### ISSUE TITLE
[BUG] TransportationName: calculate rank doesn't handle major roads that are not part of a preconfigured network

### ISSUE THREAD

**Issue by boldtrn** [onthegomap/planetiler#149]
**Describe the bug**

In Germany Planetiler is generating only few refs for major roads like motorways or trunks. The reason seems to be that Planetiler calculates the rank of a relation based on if it's part of a set of preconfigured networks (like `US:`). If these are not set, Planetiler uses other tags for hiking networks etc to figure out the rank. See the code [here](https://github.com/onthegomap/planetiler/blob/main/planetiler-basemap/src/main/java/com/onthegomap/planetiler/basemap/layers/Transportation.java#L270).

Here are two examples from Germany where this approach does not work properly which leaves major roads without road signs.
Motorway: https://www.openstreetmap.org/relation/2166961
Trunk: https://www.openstreetmap.org/relation/1506786

**Expected behavior**
As these are important roads, it would be good to have road signs for these roads.

**Screenshots**

Here is a comparison on z11 between OMT (has road signs) and Planetiler (no road signs):
<img width="557" alt="Screenshot 2022-03-26 at 12 30 56" src="https://user-images.githubusercontent.com/1553525/160238159-2b0329f0-1763-4c05-9e45-e75bce05da01.png">
<img width="662" alt="Screenshot 2022-03-26 at 12 31 19" src="https://user-images.githubusercontent.com/1553525/160238193-7bf7332c-5333-44ab-b970-21584c3c8e97.png">

**Potential fix**

The `transportation_name_minor` could be only used for minor roads. This would invalidate the fix for #145. 

So how about we apply a low rank for relations with `network=e-road` and when getting the relations of a road, we order them by rank? So right now, the default rank is 3, so maybe e-roads could be rank 4?

**Comment by boldtrn** [comment]
Haven't heard back, is this something you would like a contribution? Or is this something that wouldn't be that relevant to you?

**Comment by msbarry** [comment]
Hey sorry I just haven't had a chance to look into this. For B313 at least it looks like it does show up (because each of the ways in it also has a `ref` tag), but only starting at z12:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/1480504/162423892-e719801f-0991-4666-a621-ee36bfcadb36.png">

The reason is that openmaptiles sets a min length of 8km for transportation_name segments to appear at z11. The trunk portion of B13 is just over 9km so gets emitted, but planetiler translates that length limit to a min pixel size of the feature on a tile and that segment happens to cross a tile boundary

<img width="497" alt="image" src="https://user-images.githubusercontent.com/1480504/162429133-1243ff05-a799-4ae0-9408-bcded0916125.png">

I can see two possible fixes here:

1. Use a larger buffer for transportation_name tiles at z11 and below so the min length computation includes the full segment
2. To catch the case where a way is in a relation that has a ref but no network (and there's no ref on the way) we could add an option that breaks from openmaptiles compatibility and uses that ref on the transportation_name linestring

What do you think @boldtrn ?

**Comment by msbarry** [comment]
> Use a larger buffer for transportation_name tiles at z11 and below so the min length computation includes the full segment

Actually we already do that... it turns out that the issue here is that some onramps/offramps to B313 are tagged with `ref=B 313` (for example https://www.openstreetmap.org/way/845773628) and the line merging code stops merging at 3-way intersections and none of the line segments ends up exceeding the 8km min-lenth limit.  I'm planning to refactor the line merging code at some point (#54) so it's more robust to these kinds of issues.

In the meantime you can run planetiler with `--transportation-name-limit-merge` which groups onramps separately from main roads. When I run with that option, I can see B313 shield as low as z8

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1480504/162567339-8e64d7e2-6809-42f7-9fcf-56e66a52998a.png">

That option is disabled by default since it differs from openmaptiles, but if you find that the output is actually closer to openmaptiles with it enabled then we can enable it by default.

**Comment by boldtrn** [comment]
Thanks @msbarry for the proposal. Are there any side-effects when using `--transportation-name-limit-merge`? Is there anything I should look out for when using this parameter?

**Comment by msbarry** [comment]
Nope, it should be isolated to only affect transportation_name layer, and in general will make road labels show up a bit more frequently on the map at lower zooms. It should not be a huge difference though.

**Comment by boldtrn** [comment]
Thanks @msbarry this parameter seems to indeed improve the rendering of highway signs. Compared to OMT there are still fewer highway signs (B10 and A8 is still missing).

![Screenshot 2022-04-13 at 17 35 26](https://user-images.githubusercontent.com/1553525/163217383-8bd7b46e-7002-40ce-bba9-5af207da5842.png)

Is there be something else that I could try? If a code change is required I can create a PR as well, but I might need a hint or two :).

**Comment by msbarry** [comment]
Are you sure they're not showing up in the underlying tile data and it's not a style rendering issue? When I look in tileserver-gl I see B10 and A8:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/1480504/163291626-85427526-5a70-4628-b743-d614b38b7fe0.png">

**Comment by boldtrn** [comment]
Thanks for the hint, you are right, sorry for the troubles, they indeed appear in the data (I should have checked that).

Should we close this issue then?

**Comment by msbarry** [comment]
@boldtrn I think this is good to close for now? #298 tracks the long-term improvements to feature merging

**Comment by boldtrn** [comment]
Sounds good, thanks for your work @msbarry 👍
