### ISSUE TITLE
[BUG] `--defer-mbtiles-index-creation` does not apply to `--compact-db`

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#243]
`--defer-mbtiles-index-creation` only applies right now when `--compact-db` is not specified.  It should also apply to the 2 tables created by `--compact-db` and print the commands to run to add the indexes after planetiler runs.

**Comment by bbilger** [comment]
The index for `tiles_shallow` is being created deferred if that option is chosen, I, however, definitely missed to adjust the logging.
For `tiles_data` a primary key seemed to be the better option (clustered index). The problem with a primary key, however, is that it cannot be added afterwards.
Thinking about it, maybe it would make sense to create `tiles_data` (and also `tiles_shallow` - and also `tiles` in non-compact mode) with a primary key in case index creation is not deferred. And otherwise create the tables without primary keys, and add unique constraints later. In theory the clustered index one gets with a primary key should be more efficient and faster than a non-clustered index one gets from a unique constraint.

**Comment by msbarry** [comment]
Ah interesting, I didn't know that a primary key would behave differently than a unique index. Tiles are inserted in z,x,y order so that could work. Maybe it should use primary key then if adding the index is deferred it adds a unique index later on all 3 tables.

**Comment by bbilger** [comment]
> Would you need "without rowid" to get the benefit on z/x/y table?

Yes, my understanding of the sqlite docs is that composite primary keys would require an explicit "without rowid".

> The WITHOUT ROWID optimization is likely to be helpful for tables that have non-integer or composite (multi-column) PRIMARY KEYs...
https://www.sqlite.org/withoutrowid.html#when_to_use_without_rowid

I could work on it* this week - unless you want to work it, or you already started working on it.

*it = using primary keys in non-deferred mode, and use unique constraints in deferred mode

**Comment by bbilger** [comment]
Very promising and interesting results. Will work on it this week.
