### ISSUE TITLE
[BUG] Some of the motorway links are pointing backwards

### ISSUE THREAD

**Issue by 1T-money** [onthegomap/planetiler#296]
In the Americana map style, some of the motorway links are pointing the wrong direction. Apparently it's merging ways and disregarding the direction change and the sharp angles.

https://zelonewolf.github.io/openstreetmap-americana/#16.94/30.69606/-97.654416

https://zelonewolf.github.io/openstreetmap-americana/#16.54/30.473205/-97.702651

![image](https://user-images.githubusercontent.com/100244963/178079109-1213f7b4-b41a-461d-a949-95a08158cc5b.png)

![image](https://user-images.githubusercontent.com/100244963/178079141-bdd00b52-64d3-4dc4-a4c7-9fe8a7ed32d7.jpeg)

**Comment by msbarry** [comment]
Thanks for the details @1T-money ! The issue here is that we merge transportation linestrings with the same tags, but merging may flip the direction of the linestrings so the `oneway` tag is incorrect.

The medium-term fix is to refactor the feature merge API to make it flexible/smarter so that it knows to reverse the oneway tag when it flips a segment.

The short-term fix is just to disable line merging when oneway is present, but that fix needs to go into the openmaptiles profile which we're currently in the process of extracting to a repo in openmaptiles project.  I'll cross-post this issue to that repo to make sure they address the short term issue there.

**Comment by 1T-money** [comment]
Do you have an idea of how long it will take to get fixed?

**Comment by msbarry** [comment]
Just landed #258 so the short-term fix is tracked in https://github.com/openmaptiles/planetiler-openmaptiles/issues/10 and the long-term fix is tracked in #298
