### ISSUE TITLE
[FEATURE] Loop route back to start

### ISSUE THREAD

**Issue by nhleto** [onthegomap/planetiler#297]
New to the project but loved onthegomap when I used it to plot my run today. Not sure if this idea is in development, I looked through some feature requests and didn't see anything, but being able to reverse your route, looping back to where you started, was something I was looking for today.

**Comment by msbarry** [comment]
Thanks! This repo is just for the planetiler project for making vector tile basemaps from openstreetmap data, not onthegomap itself.

I have feedback.onthegomap.com and info at onthegomap dot com set up for people to submit sugestions like that, but not a great way to share progress or for others to comment on suggestions. I wonder if a separate onthegomap repo just for issues would work? Or maybe another service for collecting user feedback since most onthegomap users won't have a github account?
