### ISSUE TITLE
[FEATURE] Expose more detailed tile size statistics

### ISSUE THREAD

**Issue by erik** [onthegomap/planetiler#391]
**Is your feature request related to a problem? Please describe.**
When developing a new tile set, there isn't a great way to dig into why a particular tile is too large. We get a warning that a specific tile is over the configured max size, but to investigate why we need to switch to another tool that can inspect the tile and print out details about the geometry size, which layers are included, etc.

**Describe the solution you'd like**
I'd like to be able to see a breakdown of sizes (basic summary stats) by layer and zoom level at the end of a run. This could be printed to stdout (maybe formatted like [st]?), written to a separate file as JSON, or included in the MBTiles `metadata` table.

The [MBTiles spec] references another mapbox project called [geostats], which looks like a good starting point, but seems more interested in counts of features and peeking at their attribute values than on-disk size.

**Additional context**
Briefly discussed [in Slack](https://osmus.slack.com/archives/C031V9E9RMG/p1669137766947899)

[st]: https://github.com/nferraz/st
[MBTiles spec]: https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#tilestats
[geostats]: https://github.com/mapbox/mapbox-geostats#output-the-stats

**Comment by nvkelso** [comment]
While at Mapzen we developed https://github.com/tilezen/scoville for doing that type of analysis to help debug tile perf issues.

More recently I depend on aggregate charts like these for "all" layers in a given tile:

![image](https://user-images.githubusercontent.com/853051/231645011-7df1890b-75e1-492b-b982-c9c4460118ed.png)

... and then to debug which tiles have size quota violations per layer, like:

![image](https://user-images.githubusercontent.com/853051/231645136-2a47b848-a88b-4e17-b9c8-5562bdb42e5c.png)

For each layer, per zoom, it's important to have 3-5 example tile coords (and MVT links) to introspect in other software like QGIS (or PMTIles viewer) to do the deeper investigation, then iterate on the code, and rerun to see if those specific problematic tiles have been addressed.

For Tilezen v1.9 I was able to find the worst offending tiles for Places and determine problem was around Tokyo, then why, then develop plans and new software (like label grids with params and multiple sort keys) to fix. Similarly, for roads at zoom 10-13 it was was extra properties that aren't actually important for map styling at those zooms (but are at high zooms) were preventing merges.

Having a table list view of "problematic tiles" (not just a heat map) is ideal... otherwise it's like finding the needles in the haystack... even if the list just has 1-5 members.
