### ISSUE TITLE
[BUG] Charging stations won't be exported

### ISSUE THREAD

**Issue by rene-mueller** [onthegomap/planetiler#765]
**Describe the bug**
Charging stations won't be exported.

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station

**Comment by msbarry** [comment]
They should be there now? We just merged https://github.com/openmaptiles/planetiler-openmaptiles/pull/126 which upgrades to openmaptiles 3.15. One of the improvements is adding charging stations to POI layer.

**Comment by rene-mueller** [comment]
Ok, that may be the case. But no new release has been published yet.

**Comment by rene-mueller** [comment]
@msbarry when will a release be published?

**Comment by phanecak-maptiler** [comment]
> @msbarry when will a release be published?

Short reply: Soon, e.g.  roughly within a month.

Long reply: Since we do want to match what is in https://github.com/openmaptiles/openmaptiles/, we're waiting for/coordinating with @TomPohys to go through open OpenMapTiles open pull-requests (https://github.com/openmaptiles/openmaptiles/pulls). Once those needed for 3.15 are merged, I'll match them in `planetiler-openmaptiles` and then we do 3.15 releases.
